name: Check workflows

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Run actionlint
        uses: reviewdog/action-actionlint@v1
        with:
          fail_on_error: true
