name: Validate renovate.json

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  validate-renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.13.1
          cache: "yarn"

      - name: Install Renovate CLI
        run: yarn global add renovate

      - name: Validate renovate.json
        run: renovate-config-validator
